on: push
name: Main Workflow
jobs:
  gitHubActionsTest:
    name: Github Actions Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Debug
      run: |
        env
        pwd
        echo ${GOPATH}
        echo ${GOROOT}
    - name: gorun
      run: |
        go run main.go
